export const memesData = [
  {
    success: "true",
    id: 1,
    name: "Funny Face 4",
    url: "./Images/4.jpg",
    width: 1200,
    height: 1200,
  },
  {
    success: "true",
    id: 2,
    name: "Funny Face 5",
    url: "./Images/5.jpg",
    width: 1200,
    height: 1200,
  },
  {
    success: "true",
    id: 3,
    name: "Funny Face 6",
    url: "./Images/6.jpg",
    width: 1200,
    height: 1200,
  },
  {
    success: "true",
    id: 4,
    name: "Funny Face 7",
    url: "./Images/7.jpg",
    width: 1200,
    height: 1200,
  },
  {
    success: "true",
    id: 5,
    name: "Funny Face 8",
    url: "./Images/8.jpg",
    width: 1200,
    height: 1200,
  },
  {
    success: "true",
    id: 6,
    name: "Funny Face 9",
    url: "./Images/9.jpg",
    width: 1200,
    height: 1200,
  },
  {
    success: "true",
    id: 7,
    name: "Funny Face 10",
    url: "./Images/10.jpg",
    width: 1200,
    height: 1200,
  },
  {
    success: "true",
    id: 8,
    name: "Funny Face 11",
    url: "./Images/11.jpg",
    width: 1200,
    height: 1200,
  },
];
